id: A64174FD4
title: 'The Swift Steed of Garuḍa, King of Birds: An Instruction for Travelling to
  Sukhāvatī: A Visualization and Recitation of Uṣnīṣa-Sitātapatrā'
type: translation
pechas:
- IE9CE3814
- I7B70B487
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:46:22.769392
  last_modified_at: 2023-01-04 12:46:22.769409
  collections:
  - Karma Chakme Series
  - Works of Tibetan Masters
alignment_to_base:
  IE9CE3814/2547: FF9F
  I7B70B487/AA17: FF9F
